### ISSUE TITLE
May 2015 data

### ISSUE THREAD

**Issue by systemed** [dracos/split-ticket#4]
Some fares and restrictions (e.g. here on the Cotswold Line) have changed for May - any chance of an update with the new data?

**Comment by dracos** [comment]
The fares data has not yet appeared on data.atoc.org (the new timetable file is there, dated today).

**Comment by systemed** [comment]
Ah, ok. I'd spotted the new fares on brfares.com but I'm not sure where he gets his data from.

**Comment by dracos** [comment]
I'll ask :)

**Comment by dracos** [comment]
I've hopefully uploaded the May 2015 data.
