### ISSUE TITLE
Link to nationalrail restriction code descriptions

### ISSUE THREAD

**Issue by zarino** [dracos/split-ticket#8]
It would be really awesome if mentions of ticket restrictions could be auto linked to the nationalrail.co.uk page describing that restriction.

![screen shot 2016-04-21 at 10 02 13](https://cloud.githubusercontent.com/assets/739624/14703562/5a42bc82-07a8-11e6-9000-27a809a0a6eb.png)

Eg, the "(code B1)" and "(code W4)" in the screenshot above would link to http://www.nationalrail.co.uk/B1 and http://www.nationalrail.co.uk/W4 respectively.

**Comment by dracos** [comment]
Done, and yuck that this wasn't in the template, sigh at my code.
And National Rail site not mobile friendly EVEN THOUGH THEY PRINT THESE URLS ON TICKETS, FFS. I'll make some mobile friendly proxy in a sec, hang on.

**Comment by dracos** [comment]
http://traintimes.org.uk/code/B1 displays the info slightly more mobile friendly (nothing much more than allowing to display on mobile).
